#!/bin/bash
#
# Write env/.env.production with freshly generated secrets.
#
# Run this ON THE SERVER, once, before the first deploy:
#
#   ssh user@server
#   cd ~/HelloWorldAi && ./make-production-env.sh
#
# It belongs on the server because that is the only machine that should ever
# hold these values. deploy.sh excludes env/.env.* from the sync for the same
# reason: a local copy travelling up would overwrite the server's secrets,
# including an artifact encryption key that cannot be recovered.

set -euo pipefail

TARGET="$(cd "$(dirname "$0")" && pwd)/env/.env.production"

# Never clobber. Overwriting this file silently swaps every node's session
# secret and, if artifact encryption is on, makes every stored dataset
# unreadable with no way back.
if [ -e "$TARGET" ]; then
  echo "❌ $TARGET already exists."
  echo "   Refusing to overwrite it. Read it, or move it aside deliberately."
  exit 1
fi

# openssl first: it is on every server this will ever run on, and does not
# care which Python is installed or what "python3" resolves to.
gen() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-43
  else
    "$PY" -c "import secrets;print(secrets.token_urlsafe(32))"
  fi
}

genkey() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32
  else
    "$PY" -c "import base64,os;print(base64.b64encode(os.urandom(32)).decode())"
  fi
}

# Only needed if openssl is missing, but resolve it before we rely on it.
PY=""
for candidate in python3 python; do
  if command -v "$candidate" >/dev/null 2>&1 && "$candidate" -c "" 2>/dev/null; then
    PY="$candidate"; break
  fi
done
if ! command -v openssl >/dev/null 2>&1 && [ -z "$PY" ]; then
  echo "❌ Need either openssl or python to generate secrets."
  exit 1
fi

NODE_TOKEN_SECRET="$(gen)"

# Artifact encryption is optional and the service runs either way. It is on by
# default here because a fresh deployment has no stored data to lose, and this
# is the one moment where turning it on costs nothing. Blank it if you would
# rather not carry a key you must never lose.
ARTIFACT_ENCRYPTION_KEY="$(genkey)"

mkdir -p "$(dirname "$TARGET")"
umask 077                      # nobody else on the box needs to read this

cat > "$TARGET" <<EOF
# Generated by make-production-env.sh. Not in git, and not synced by deploy.sh.
#
# Back this file up somewhere other than this server, together with a dump of
# the database. The database is not readable without the key below.

ENV=production
USE_DOCKER=true

# --- addresses ------------------------------------------------------------
# Only Caddy listens on the outside; these stay on the loopback address.
BIND_ADDRESS=127.0.0.1
COORDINATOR_URL=http://coordinator:8100
NODE_URL=http://node:9100
DASHBOARD_PORT=3000
COORDINATOR_PORT=8100
NODE_PORT=9100

# --- database -------------------------------------------------------------
MONGO_DB=NodeDbProd

# --- secrets --------------------------------------------------------------
# Signs the tokens nodes use to prove who they are. Unset, a throwaway key is
# made at startup and every node is logged out on every restart.
NODE_TOKEN_SECRET=$NODE_TOKEN_SECRET

# Encrypts submitted datasets before they are written to the database. Optional
# -- the service runs either way, and the send-work page tells submitters which
# is true. There is no recovery path if this is lost.
ARTIFACT_ENCRYPTION_KEY=$ARTIFACT_ENCRYPTION_KEY

# --- signing in with GitHub (optional) ------------------------------------
# Blank is a working configuration: the key in the browser is the identity, and
# the workspace hides the sign-in panel entirely. Fill these in to let people
# sign in, so their work has an owner and follows them between machines. No key
# is ever stored here -- an account links to the digests the coordinator
# already keeps.
#
# Register an OAuth app at https://github.com/settings/developers. Its Redirect
# URI must be exactly https://your.domain/auth/github/callback -- GitHub
# compares it character for character. Leave wildcard matching and device flow
# off. There is no scopes field on that form; the sign-in asks for none.
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=

# The address browsers reach this on, no trailing slash. The coordinator cannot
# work this out for itself -- from inside the compose network it only knows
# http://coordinator:8100 -- and sign-in needs the real one to send GitHub back
# to. Required only if the two lines above are filled in.
#   PUBLIC_URL=https://your.domain
PUBLIC_URL=

# --- behaviour ------------------------------------------------------------
HEARTBEAT_INTERVAL=60
TASK_POLL_INTERVAL=10
DATASET_RETENTION_MINUTES=60
HOLDOUT_FRACTION=0.2
EOF

chmod 600 "$TARGET"

echo "✅ Wrote $TARGET (mode 600)"
echo
echo "   Two secrets were generated. Back this file up somewhere other than"
echo "   this machine, alongside a database dump -- one is useless without the"
echo "   other, and the encryption key cannot be regenerated."
echo
echo "   Then set your hostname and deploy:"
echo "     DOMAIN=your.domain docker compose -p helloworldai -f docker/docker-compose.yml up -d"
